config/routes.rb
Rails.application.routes.draw do
  resources :trades do
    collection do
        post :create_trade_via_ajax_request
      end
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  get 'welcome/welcome_page'

  root 'users#index'

    resources :users do
      collection do
        post 'update_data'
        get 'notify_user'
        get 'profile'
      end
    end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trades
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trades_controller.rb
class TradesController < InheritedResources::Base


  def create_trade_via_ajax_request
  	@trade = Trade.new(trade_params)
    if @trade.save
    	flash[:message] = "Trade submitted successfully"
    else
    	flash[:alert] = "Sorry Trade cant be submitted"
    end
    redirect_to profile_users_path
  end

  private

    def trade_params
      params.require(:trade).permit(:avatar, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def update_data
    user = User.new(user_params)
    user.password = "password"
    user.save!
    redirect_to notify_user_users_path, :flash => { :success => "User success" }
  end

  def notify_user
  end

  def profile
  end

  def update
  end

  private
  def user_params
    params.require(:user).permit!
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def welcome_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<head>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Axe Capital Research Team</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <% if current_user.present? %>
          <li><%= link_to "Profile", profile_users_path %></li>
          <% if current_user.trade_access == true %>
            <li><%= link_to "Trades", trades_path %></li>
          <% end %>
        <% else %>
          <li><a href="#">Page 1</a></li>
          <li><a href="#">Page 2</a></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: 'DELETE' %></li>
        <% else %>
          <!-- <li><%= link_to "Admin Login", new_admin_user_session_path %> </li> -->
          <li><%= link_to "Trader Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRmoneymanagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => '/layouts/header' %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br />
  <div class="field form-group">
    <%= f.label :Screenshot_Image %><br>
    <%= f.file_field :avatar, :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :cols => '50', :rows => "10", :class => "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Create Trade", :class => "btn btn-lg btn-success" %>
  </div>
<% end %><br />

app/views/trades/edit.html.erb
<h1>Editing Trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trades</h1>

<table border="1">
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td>
          <%#= trade.avatar %>
          <%= image_tag(trade.avatar, :alt => "rss feed", :size => "60x60") %>
        </td>
        <td><%= trade.description %></td>
        <td><%= current_user.first_name %></td>
        <td><%= link_to 'Show', trade %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New Trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Avatar:</strong>
  <%= @trade.avatar %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trade.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @trade.user_id %>
</p>

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>

app/views/users/notify_user.html.erb
<h1> CR Money Management </h1>

Your Application is being reviewed, our representative is will contact you soon.

app/views/users/profile.html.erb
<div>
    <div class="row">
    
        <div style="padding-top:50px;"> </div>
        <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="media">
                        <div align="center">
                            <img class="thumbnail img-responsive" src="https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png" width="300px" height="300px">
                        </div>
                        <div class="media-body">
                            <hr>
                            <h3><strong>Bio</strong></h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vel gravida metus, non ultrices sapien. Morbi odio metus, dapibus non nibh id amet.</p>
                            <hr>
                            <h3><strong>Location</strong></h3>
                            <p>Earth</p>
                            <hr>
                            <h3><strong>Gender</strong></h3>
                            <p>Unknown</p>
                            <hr>
                            <h3><strong>Birthday</strong></h3>
                            <p>January 01 1901</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <span>
                        <h1 class="panel-title pull-left" style="font-size:30px;"><% if current_user.first_name.present? %> <%= current_user.first_name %> <% else %> User Name <% end %>  <small><%= current_user.email %></small> <i class="fa fa-check text-success" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="John Doe is sharing with you"></i></h1>
                        <div class="dropdown pull-right">
                            <button class="btn btn-success " type="button" id="dropdownMenu1"  aria-haspopup="true" aria-expanded="true">
                                Edit Profile
                            </button>
                            <button class="btn btn-success " type="button" id="dropdownMenu1"  aria-haspopup="true" aria-expanded="true", data-toggle="modal", data-target= "#WidgetGenModal">
                              Submit Trade
                            </button>
                        </div>
                    </span>
                    <br><br>
                    <% if current_user.phone_number.present? %> <%= current_user.phone_number %> <% else %> Ph 1234567890 <% end %>  
                    <br><br><hr>
                    <span class="pull-left">
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-fw fa-files-o" aria-hidden="true"></i> Posts</a>
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-fw fa-picture-o" aria-hidden="true"></i> Photos <span class="badge">42</span></a>
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-fw fa-users" aria-hidden="true"></i> Contacts <span class="badge">42</span></a>
                    </span>
                    <span class="pull-right">
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-lg fa-at" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Mention"></i></a>
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-lg fa-envelope-o" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Message"></i></a>
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-lg fa-ban" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Ignore"></i></a>
                    </span>
                </div>
            </div>
            <hr>

            <!---Trades  -->
            <% current_user.trades.all.order("created_at desc").each do |trade| %>
             <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-left">
                        <a href="#">
                            <img class="media-object img-circle" src="https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png" width="50px" height="50px" style="margin-right:8px; margin-top:-5px;">
                        </a>
                    </div>
                    <h4><a href="#" style="text-decoration:none;"><strong>John Doe</strong></a> – <small><small><a href="#" style="text-decoration:none; color:grey;"><i><i class="fa fa-clock-o" aria-hidden="true"></i> <%= time_ago_in_words(trade.created_at) %> ago</i></a></small></small></h4>
                    <span>
                        <div class="navbar-right">
                            <div class="dropdown">
                                <button class="btn btn-link btn-xs dropdown-toggle" type="button" id="dd1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    <i class="fa fa-cog" aria-hidden="true"></i>
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dd1" style="float: right;">
                                    <li><a href="#"><i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i> Report</a></li>
                                    <li><a href="#"><i class="fa fa-fw fa-ban" aria-hidden="true"></i> Ignore</a></li>
                                    <li><a href="#"><i class="fa fa-fw fa-bell" aria-hidden="true"></i> Enable notifications for this post</a></li>
                                    <li><a href="#"><i class="fa fa-fw fa-eye-slash" aria-hidden="true"></i> Hide</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#"><i class="fa fa-fw fa-trash" aria-hidden="true"></i> Delete</a></li>
                                </ul>
                            </div>
                        </div>
                    </span>
                    <hr>
                    <div class="post-content">
                        <p><%= trade.description %></p>
                    </div>
                    <%= image_tag(trade.avatar, :alt => "trade image", width: "300px", height: "300px") %>
                    <hr>
                    <div>
                        <div class="pull-right btn-group-xs">
                            <a class="btn btn-default btn-xs"><i class="fa fa-heart" aria-hidden="true"></i> Like</a>
                            <a class="btn btn-default btn-xs"><i class="fa fa-retweet" aria-hidden="true"></i> Reshare</a>
                            <a class="btn btn-default btn-xs"><i class="fa fa-comment" aria-hidden="true"></i> Comment</a>
                        </div>
                        <div class="pull-left">
                            <p class="text-muted" style="margin-left:5px;"><i class="fa fa-globe" aria-hidden="true"></i> Public</p>
                        </div>
                        <br>
                    </div>
                    <hr>
                    <div class="media">
                        <div class="pull-left">
                            <a href="#">
                                <img class="media-object img-circle" src="https://lut.im/7JCpw12uUT/mY0Mb78SvSIcjvkf.png" width="35px" height="35px" style="margin-left:3px; margin-right:-5px;">
                            </a>
                        </div>
                        <div class="media-body">
                            <textarea class="form-control" rows="1" placeholder="Comment"></textarea>
                        </div>
                    </div>
                </div>
             </div>

             
            <% end %>



        </div>
    </div>
</div>


<div class="modal fade" id="WidgetGenModal" tabindex="-1" role="dialog" aria-labelledby="widgetGenModal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="widgetGenModal"><div class="btn btn-danger btn-xs">NEW</div> Create New Trade</h3>
            Please Upload Screenshots and submit
          </div>
          <div class="modal-body" id="WidgetGenModalBody">
            <%= form_for  :trade ,url: create_trade_via_ajax_request_trades_path, :remote => true  do |f| %>
             <%= f.label :trade_screenshots  %>
              <label class="btn btn-primary">
                Add a Screenshot
                <span style="display:none;">
                  <%= f.file_field :avatar %>
                </span>
              </label>
            
              <div class="field">
                <%= f.label :description %>
                <%= f.text_area :description, class: "form-control" %>
              </div>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <br>
              <br>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              <div class="actions">
        <%= f.submit %>
      </div>

            <% end %>
          </div>
          <div class="modal-footer">
            <div id="test"></div>
            <div class="clearfix visible-xs"></div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->


<style type="text/css">
    .mainbody {
    background:#f0f0f0;
}
/* Special class on .container surrounding .navbar, used for positioning it into place. */
.navbar-wrapper {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 20;
  margin-left: -15px;
  margin-right: -15px;
}

/* Flip around the padding for proper display in narrow viewports */
.navbar-wrapper .container {
  padding-left: 0;
  padding-right: 0;
}
.navbar-wrapper .navbar {
  padding-left: 15px;
  padding-right: 15px;
}

.navbar-content
{
    width:320px;
    padding: 15px;
    padding-bottom:0px;
}
.navbar-content:before, .navbar-content:after
{
    display: table;
    content: "";
    line-height: 0;
}
.navbar-nav.navbar-right:last-child {
    margin-right: 15px !important;
}
.navbar-footer 
{
    background-color:#DDD;
}
.navbar-footer-content { padding:15px 15px 15px 15px; }
.dropdown-menu {
padding: 0px;
overflow: hidden;
}

.brand_network {
    color: #9D9D9D;
    float: left;
    position: absolute;
    left: 70px;
    top: 30px;
    font-size: smaller;
}

.post-content {
    margin-left:58px;
}

.badge-important {
    margin-top: 3px;
    margin-left: 25px;
    position: absolute;
}

body {
    background-color: #e8e8e8;
}
</style>

<script type="text/javascript">
    
  $(document).on("click","#submit_trade_button",function() {
      $("#my-form").submit();
  });

    $(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>